// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import ()

type Verse struct {
	ID          int64
	Translation string
	Book        string
	Chapter     int64
	Verse       int64
	Content     string
}
