// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: bible/v1/bible.proto

package biblev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translation string `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	Book        string `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Chapter     int32  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse       int32  `protobuf:"varint,4,opt,name=verse,proto3" json:"verse,omitempty"`
	Content     string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Verse) Reset() {
	*x = Verse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_v1_bible_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verse) ProtoMessage() {}

func (x *Verse) ProtoReflect() protoreflect.Message {
	mi := &file_bible_v1_bible_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verse.ProtoReflect.Descriptor instead.
func (*Verse) Descriptor() ([]byte, []int) {
	return file_bible_v1_bible_proto_rawDescGZIP(), []int{0}
}

func (x *Verse) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *Verse) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *Verse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *Verse) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *Verse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetChapterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translation string `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	Book        string `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Chapter     int32  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *GetChapterRequest) Reset() {
	*x = GetChapterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_v1_bible_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequest) ProtoMessage() {}

func (x *GetChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bible_v1_bible_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequest.ProtoReflect.Descriptor instead.
func (*GetChapterRequest) Descriptor() ([]byte, []int) {
	return file_bible_v1_bible_proto_rawDescGZIP(), []int{1}
}

func (x *GetChapterRequest) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *GetChapterRequest) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *GetChapterRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type GetChapterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verses []*Verse `protobuf:"bytes,1,rep,name=verses,proto3" json:"verses,omitempty"`
}

func (x *GetChapterResponse) Reset() {
	*x = GetChapterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_v1_bible_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterResponse) ProtoMessage() {}

func (x *GetChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bible_v1_bible_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterResponse.ProtoReflect.Descriptor instead.
func (*GetChapterResponse) Descriptor() ([]byte, []int) {
	return file_bible_v1_bible_proto_rawDescGZIP(), []int{2}
}

func (x *GetChapterResponse) GetVerses() []*Verse {
	if x != nil {
		return x.Verses
	}
	return nil
}

var File_bible_v1_bible_proto protoreflect.FileDescriptor

var file_bible_v1_bible_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x69, 0x62, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x87, 0x01, 0x0a, 0x05, 0x56, 0x65, 0x72, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x22,
	0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x06, 0x76, 0x65, 0x72, 0x73, 0x65, 0x73, 0x32, 0x59,
	0x0a, 0x0c, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x62,
	0x69, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x69, 0x62, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x62, 0x69, 0x62,
	0x6c, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65,
	0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x69,
	0x62, 0x6c, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bible_v1_bible_proto_rawDescOnce sync.Once
	file_bible_v1_bible_proto_rawDescData = file_bible_v1_bible_proto_rawDesc
)

func file_bible_v1_bible_proto_rawDescGZIP() []byte {
	file_bible_v1_bible_proto_rawDescOnce.Do(func() {
		file_bible_v1_bible_proto_rawDescData = protoimpl.X.CompressGZIP(file_bible_v1_bible_proto_rawDescData)
	})
	return file_bible_v1_bible_proto_rawDescData
}

var file_bible_v1_bible_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bible_v1_bible_proto_goTypes = []interface{}{
	(*Verse)(nil),              // 0: bible.v1.Verse
	(*GetChapterRequest)(nil),  // 1: bible.v1.GetChapterRequest
	(*GetChapterResponse)(nil), // 2: bible.v1.GetChapterResponse
}
var file_bible_v1_bible_proto_depIdxs = []int32{
	0, // 0: bible.v1.GetChapterResponse.verses:type_name -> bible.v1.Verse
	1, // 1: bible.v1.BibleService.GetChapter:input_type -> bible.v1.GetChapterRequest
	2, // 2: bible.v1.BibleService.GetChapter:output_type -> bible.v1.GetChapterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bible_v1_bible_proto_init() }
func file_bible_v1_bible_proto_init() {
	if File_bible_v1_bible_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bible_v1_bible_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bible_v1_bible_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChapterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bible_v1_bible_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChapterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bible_v1_bible_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bible_v1_bible_proto_goTypes,
		DependencyIndexes: file_bible_v1_bible_proto_depIdxs,
		MessageInfos:      file_bible_v1_bible_proto_msgTypes,
	}.Build()
	File_bible_v1_bible_proto = out.File
	file_bible_v1_bible_proto_rawDesc = nil
	file_bible_v1_bible_proto_goTypes = nil
	file_bible_v1_bible_proto_depIdxs = nil
}
